kind: pipeline
type: docker
name: default

steps:
  - name: say-hello
    image: alpine
    commands:
      - echo "Hello from Drone CI!"

  - name: check-files
    image: alpine
    commands:
      - ls -la
      - echo "All files listed."

  - name: build-image
    image: gcr.io/kaniko-project/executor:latest
    commands:
      - /kaniko/executor --context $DRONE_WORKSPACE --dockerfile $DRONE_WORKSPACE/Dockerfile --no-push --snapshotMode=redo

  - name: scan-image
    image: aquasec/trivy:latest
    commands:
      - trivy image --exit-code 1 --severity HIGH,CRITICAL your-image:latest || true

  - name: goodbye
    image: alpine
    commands:
      - echo "Goodbye from Drone pipeline!"
